
[package]
authors = ["Jamil Ahmed <jamil.ahmed.ja28@gmail.com>"]
edition = "2018"
name = "dth_sensor_rust"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.6"
cortex-m-rt = "0.6.3"
panic-itm = "0.4.0"

[dependencies.f3]
features = ["rt"]
version = "0.6.1"
